---
- name: configure interface
  hosts: nip-xrv9k
  tasks:
          - name: configure interface settings
            iosxr_config:
                    lines:
                            - description {{ description }}
                            - ip address {{ ipaddress }}
                            - no shutdown
                    parents: interface {{ interface }}
