---
- name: deconfigure interface
  hosts: nip-xrv9k
  tasks:
          - name: deconfigure interface settings
            iosxr_config:
                    lines:
                            - no description
                            - no ip address
                            - shutdown
                    parents: interface GigabitEthernet0/0/0/1
